name: Backup to HuggingFace

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours (UTC)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backup script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python script.py
