name: Daily Minecraft Backup Upload

on:
  schedule:
    - cron: '0 20 * * *'  # 2 AM Bangladesh Time (UTC+6)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-api-python-client huggingface_hub

      - name: Run sync script
        env:
          GDRIVE_KEY_JSON: ${{ secrets.GDRIVE_KEY_JSON }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python sync.py
